import figma, { html } from "@figma/code-connect/html"

/**
 * USA Process List Counter
 * @see https://designsystem.digital.gov/components/process-list/
 *
 * The counter is rendered automatically by USWDS via the <ol>
 * ordered list and CSS counter styles. No extra markup needed.
 */
figma.connect(
  "https://www.figma.com/design/qb6gYgys3iMWhBkxU0w9li/USWDS-Design-Kit-Exp?node-id=964-6450",
  {
    props: {
      number: figma.string("number"),
    },
    example: (props) => html`
<!-- Step ${props.number}: Counter auto-generated by USWDS CSS -->
<ol class="usa-process-list">
  <li class="usa-process-list__item">
    <h4 class="usa-process-list__heading">Step heading</h4>
    <p>Step description text.</p>
  </li>
</ol>
`,
  },
)
